### ISSUE TITLE
frontend_https key not defined

### ISSUE THREAD

**Issue by Marc69** [clustervision/luna#40]
**Version:** 700bc5b
I expected there to be a default value. Should I always set it manually? Otherwise luna cluster show will fail: 
```
[root@tmaster2-controller01 luna]# luna cluster show 
Traceback (most recent call last):
  File "/usr/sbin/luna", line 1916, in <module>
    res = call_fun(**args)
  File "/usr/sbin/luna", line 173, in cluster_show
    https = out_json.pop('frontend_https')
KeyError: 'frontend_https'
[root@tmaster2-controller01 luna]# luna cluster show -R
{
    "_id": {
        "$oid": "59720e385bfcd854cb5db582"
    },
    "_use_": {
        "network": {
            "59720e8d5bfcd854d9f34cda": 1
        }
    },
    "_usedby_": {
        "group": {
            "599408125bfcd875943acb70": 1
        },
        "network": {
            "59720e8d5bfcd854d9f34cda": 1
        },
        "node": {
            "59941aaa5bfcd80b24404a16": 1
        },
        "osimage": {
            "5994055b5bfcd81f5eb4af0d": 1
        }
    },
    "cluster_ips": null,
    "comment": null,
    "db_version": 1.2,
    "debug": 0,
    "dhcp_net": "59720e8d5bfcd854d9f34cda",
    "dhcp_range_end": 65480,
    "dhcp_range_start": 32769,
    "frontend_address": "10.36.255.254",
    "frontend_port": "7050",
    "lweb_num_proc": 0,
    "lweb_pidfile": "/run/luna/lweb.pid",
    "name": "general",
    "named_include_file": "/etc/named.luna.zones",
    "named_zone_dir": "/var/named",
    "nodedigits": 3,
    "nodeprefix": "node",
    "path": "/opt/luna",
    "server_port": 7051,
    "torrent_listen_port_max": 7200,
    "torrent_listen_port_min": 7052,
    "torrent_pidfile": "/run/luna/ltorrent.pid",
    "tracker_interval": 10,
    "tracker_maxpeers": 200,
    "tracker_min_interval": 5,
    "user": "luna"
```
```
[root@tmaster2-controller01 luna]# luna cluster change --frontend_https n
[root@tmaster2-controller01 luna]# luna cluster show
+----------------------------+---------------------------+
| Parameter                  | Value                     |
+----------------------------+---------------------------+
| cluster_ips                | -                         |
| debug                      | 0                         |
| dhcp_net                   | [cluster]                 |
| dhcp_range_end             | 10.36.255.200             |
| dhcp_range_start           | 10.36.128.1               |
| frontend_address           | 10.36.255.254             |
| frontend_https             | no                        |
| frontend_port              | 7050                      |
| lweb_num_proc              | 0                         |
| lweb_pidfile               | /run/luna/lweb.pid        |
| named_include_file         | /etc/named.luna.zones     |
| named_zone_dir             | /var/named                |
| nodedigits                 | 3                         |
| nodeprefix                 | node                      |
| path                       | /opt/luna                 |
| server_port                | 7051                      |
| torrent_listen_port_max    | 7200                      |
| torrent_listen_port_min    | 7052                      |
| torrent_pidfile            | /run/luna/ltorrent.pid    |
| tracker_interval           | 10                        |
| tracker_maxpeers           | 200                       |
| tracker_min_interval       | 5                         |
| user                       | luna                      |
| comment                    | -                         |
+----------------------------+---------------------------+
```

**Comment by dchirikov** [comment]
it creates value here:
https://github.com/clustervision/luna/blob/700bc5b72087e66b7318a431a7533d0fd892da11/luna/cluster.py#L158
