### ISSUE TITLE
v1.2-2.1 : makedhcp ERROR

### ISSUE THREAD

**Issue by 3nder** [clustervision/luna#68]
Hello,

The command makedhcp is not working. It says something like : Start of the range does not belong to network, but it does.

[root@luna ~]# luna network add -n cluster -N 10.141.0.0 -P 24
[root@luna ~]# luna network show cluster
+----------------+-----------------+
| Parameter      | Value           |
+----------------+-----------------+
| name           | cluster         |
| NETWORK        | 10.141.0.0      |
| PREFIX         | 24              |
| include        | -               |
| ns_hostname    | luna            |
| ns_ip          | 10.141.0.254    |
| rev_include    | -               |
| version        | 4               |
| comment        |                 |
+----------------+-----------------+

[root@luna ~]# luna cluster makedhcp --network cluster -s 10.141.0.1 -e 10.141.0.240
ERROR:luna.utils.ip:Cannot convert IP '177012736' to C format
ERROR:luna.cluster:Start of the range does not belong to network.
ERROR:luna.cluster:Unable to create DHCP config
ERROR:root:Error on creating DHCP config.

Thank you for help.

Best.

**Comment by dchirikov** [comment]
Hi 3nder,

This line is weird: `Cannot convert IP '177012736' to C format`. Just to be sure, are you using Python 2? Which OS are you using?

Just checked sequence you shared
```
# luna cluster delete --force
# luna cluster init --frontend_address 10.141.0.254
# luna network add -n cluster -N 10.141.0.0 -P 24
# luna cluster makedhcp --network cluster -s 10.141.0.1 -e 10.141.0.240
INFO:root:Stopping local dhcpd.
INFO:root:Remove lease files
INFO:root:Starting local dhcpd.
```

**Comment by 3nder** [comment]
Hello Dmitry,

I'm under CentOS 7.4, and python 2.7.5.

When i try to run the command, i have this error :
[root@luna ~]# luna cluster delete --force
Traceback (most recent call last):
  File "/usr/sbin/luna", line 1922, in <module>
    res = call_fun(**args)
  File "/usr/sbin/luna", line 133, in cluster_delete
    return cluster.delete(args['force'])
  File "/usr/lib/python2.7/site-packages/luna/cluster.py", line 689, in delete
    self._mongo_db.connection.drop_database(db_name)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 2624, in __call__
    self.__name.split(".")[-1])
TypeError: 'Collection' object is not callable. If you meant to call the 'drop_database' method on a 'Collection' object it is failing because no such method exists.

I tried to delete the network, and re create again, but i have the same error.

Here all the version of the modules :
python_hostlist-1.17-py2.7
tornado-4.2.1-py2.7
pymongo-3.4.0
luna-1.2-2.el7.centos.x86_64.rpm

Thank you,

Best.

**Comment by 3nder** [comment]
OK, i have found the problem. It was pymongo-3.4.0. Downgrade to 2.5.2, it is working fine now.

[root@luna ~]# luna cluster show
+----------------------------+---------------------------+
| Parameter                  | Value                     |
+----------------------------+---------------------------+
| cluster_ips                | -                         |
| debug                      | 0                         |
| dhcp_net                   | [cluster]                 |
| dhcp_range_end             | 10.141.0.240              |
| dhcp_range_start           | 10.141.0.1                |
| frontend_address           | 10.141.0.252              |
| frontend_https             | no                        |
| frontend_port              | 7050                      |
| lweb_num_proc              | 0                         |
| lweb_pidfile               | /run/luna/lweb.pid        |
| named_include_file         | /etc/named.luna.zones     |
| named_zone_dir             | /var/named                |
| nodedigits                 | 3                         |
| nodeprefix                 | node                      |
| path                       | /opt/luna                 |
| server_port                | 7051                      |
| torrent_listen_port_max    | 7200                      |
| torrent_listen_port_min    | 7052                      |
| torrent_pidfile            | /run/luna/ltorrent.pid    |
| tracker_interval           | 10                        |
| tracker_maxpeers           | 200                       |
| tracker_min_interval       | 5                         |
| user                       | luna                      |
| comment                    | -                         |
+----------------------------+---------------------------+

**Comment by dchirikov** [comment]
This is weird. This line should prevent installing newer pymongo:
https://github.com/clustervision/luna/blob/dev/rpm/luna.spec.in#L46
